GET http://localhost:3000/ HTTP/1.1

POST http://localhost:3000/auth/ HTTP/1.1
Content-Type: application/json

{
    "email":"ex@example.com",
    "password":"password",
    "password_confirmation":"password"
}
